@startuml

hide empty members

class Network {
    - String id
    - String name
    - Location location
    - String href
    - String[] company
    - String gbfsHref
    - boolean ebikes
}

class Location {
    - String city
}

class NetworksResponse {
    - List<Network> networks
}

class NetworkResponse {
    - Network network
}

Network *-- "1" Location : location
NetworksResponse *-- "*" Network : networks
NetworkResponse *-- "1" Network : network

@enduml